### ISSUE TITLE
Licence unclear

### ISSUE THREAD

**Issue by szabi** [EliasKhoury/RRB-Trees-in-Haskell#4]
Hey, Elias,

would you mind adding a licence file to make licencing conditons clear?

(Looking at the Haskell ecosystem BSD-3 or MIT seem popular).

Thank you!

**Comment by EliasKhoury** [comment]
Hi André,

Thanks for pointing this out, I made this project when I was a student and quite ignorant of such things. I've added the MIT license so you can go nuts with this source code. 

It's pretty cool to hear that this code is useful to someone :) 

Reference commit:
[SHA: a065367333bce8d09d6d3c80ba8c5fa8e0524dee](https://github.com/EliasKhoury/RRB-Trees-in-Haskell/commit/a065367333bce8d09d6d3c80ba8c5fa8e0524dee)

**Comment by szabi** [comment]
Thanks!

I'll probably go for finger trees in the end, but this is clearer now if anyone else wants to look into RRB-trees in Haskell.
